### PR TITLE
DESTDIR set to default empty so we do not use // in paths

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
please ignore for now -- work in progress.

**Comment by kacf** [comment]
The common way for build systems is to express paths as `$(DESTDIR)$(datadir)` for example, so in that case you need the `/`. If we want to adhere to the common practice is to change the line below (and others) to

```diff
-moduledir ?= $(DESTDIR)/usr/share/mender/modules/v3
+moduledir ?= $(DESTDIR)usr/share/mender/modules/v3
```

Don't ask me why it is like this, but it is standard practice in autotools and most installation systems inspired by it.

**Comment by merlin-northern** [comment]
> The common way for build systems is to express paths as `$(DESTDIR)$(datadir)` for example, so in that case you need the `/`. If we want to adhere to the common practice is to change the line below (and others) to
> 
> ```diff
> -moduledir ?= $(DESTDIR)/usr/share/mender/modules/v3
> +moduledir ?= $(DESTDIR)usr/share/mender/modules/v3
> ```
> 
> Don't ask me why it is like this, but it is standard practice in autotools and most installation systems inspired by it.

yes. thanks. thats what I am doing in the 3 'DESTDIR' PRs, try to make it as autoconf/automake does it and avoid '//'. the other 2 PRs follow what you mention. this one for some reason I missed. good catch.

**Comment by kacf** [comment]
My point is that this is *not* how they do it. They do it like this:

```
DESTDIR=/
bindir=$(DESTDIR)usr
```

And I think we should do the same. For example Yocto may set `DESTDIR` outside of our control, and then it will include the slash.

**Comment by kacf** [comment]
Oops, sorry, I'm wrong, what they do is actually this:

```
bindir=/usr/bin
...
install -m 755 mybinary $(DESTDIR)$(bindir)
```

So then you're right, the slash should be gone.

**Comment by oleorhagen** [comment]
@merlin-northern this is good to go, right?

**Comment by merlin-northern** [comment]
> @merlin-northern this is good to go, right?

I believe so, it was a triplet of PRs I wanted to merge them together.

**Comment by oleorhagen** [comment]
@kacf

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
This is just too old. Closing.

@merlin-northern Feel free to refresh and submit a new PR :+1:

**Pull request closed without merging**
