### PR TITLE
[pipeline]: Trigger Docker images publish on merges

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by kacf** [comment]
Isn't Yocto supposed to use the latest stable of this module? I think this trigger is not needed, if so then only on tags.

**Comment by lluiscampos** [comment]
> Isn't Yocto supposed to use the latest stable of this module? I think this trigger is not needed, if so then only on tags.

You are right but that only applies once we release. For now we are using AUTOREV (master), and without this trigger we risk integration tests being developed (not Fabio's "acceptance" test, but the new task) using an outdated image.

I am okey with not merging this nor mender-qa related PR. But then we have to make sure that after every fix in mender-configure-module we manually trigger a build.

**Comment by kacf** [comment]
I think in this case we should do that. We are almost done here, anyway.

**Comment by lluiscampos** [comment]
Okey.

**Pull request closed without merging**
