### PR TITLE
test: The six installation error during integration tests fix

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: None
Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]

**Comment by merlin-northern** [comment]
> No, don't do this. Update the submodule SHA instead. We need to keep it stable in case integration gets changes that we need to adapt to.

ok you mean something like that: https://github.com/mendersoftware/mender-configure-module/pull/50/commits/9e54b1abba4496d507cecd203195ccbf014820d4 ?

**Comment by merlin-northern** [comment]
@alfrunes there is a number of new problems:

```
b'stat /builds/Northern.tech/Mender/mender-configure-module/tests/integration/mender_integration/docker-compose.config.yml: no such file or directory\n'
```

was removed from integration with `f6b1683718966fa132aae47889f1ab6277236b48` in 2021

it is referenced here: https://github.com/mendersoftware/mender-configure-module/blob/master/tests/integration/tests/conftest.py#L88

**Review by kacf — APPROVED** [review]
> ok you mean something like that: [9e54b1a](https://github.com/mendersoftware/mender-configure-module/commit/9e54b1abba4496d507cecd203195ccbf014820d4) ?

Exactly, thank you!

New problems will just need adaptation.

**Review by alfrunes — APPROVED** [review]

**Comment by alfrunes** [comment]
There's one more problem with the integration tests; the sub-module update removed the deviceconfig compose file (it's now included in the default stack). You can simply remove this extra compose file argument [here](https://github.com/mendersoftware/mender-configure-module/blob/651e5a7d4628dabac725d50d7d6a48ce93ec0130/tests/integration/tests/conftest.py#L88).

**Comment by merlin-northern** [comment]
> There's one more problem with the integration tests; the sub-module update removed the deviceconfig compose file (it's now included in the default stack). You can simply remove this extra compose file argument [here](https://github.com/mendersoftware/mender-configure-module/blob/651e5a7d4628dabac725d50d7d6a48ce93ec0130/tests/integration/tests/conftest.py#L88).

yes, basically same comment: https://github.com/mendersoftware/mender-configure-module/pull/50#issuecomment-1175838287 :)

**Comment by merlin-northern** [comment]
> > There's one more problem with the integration tests; the sub-module update removed the deviceconfig compose file (it's now included in the default stack). You can simply remove this extra compose file argument [here](https://github.com/mendersoftware/mender-configure-module/blob/651e5a7d4628dabac725d50d7d6a48ce93ec0130/tests/integration/tests/conftest.py#L88).
> 
> yes, basically same comment: [#50 (comment)](https://github.com/mendersoftware/mender-configure-module/pull/50#issuecomment-1175838287) :)

thanks for pushing that -- only now I had some time to get back here.

**Pull request merged**
